name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    name: Linting
    uses: sapphiredev/.github/.github/workflows/reusable-lint.yml@main

  MarkdownLint:
    uses: sapphiredev/.github/.github/workflows/reusable-yarn-job.yml@main
    with:
      script-name: lint:md-no-fix

  formatting:
    name: Prettier Validation
    uses: sapphiredev/.github/.github/workflows/reusable-prettier.yml@main
