name: Update Git Submodules

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  SubmoduleSync:
    name: Update Git Submodules
    runs-on: ubuntu-latest
    if: github.repository_owner == 'sapphiredev'
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SKYRA_TOKEN }}
          submodules: 'recursive'
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          registry-url: https://registry.yarnpkg.com/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Configure Git
        run: |
          git remote set-url origin "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git"
          git config --local user.email "${GITHUB_EMAIL}"
          git config --local user.name "${GITHUB_USER}"
        env:
          GITHUB_USER: github-actions[bot]
          GITHUB_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update all submodules
        run: yarn update-submodules
      - name: Update lockfile
        run: yarn install --mode=update-lockfile
      - name: Commit and push any changes
        run: |
          git add --all .;
          if ! git diff-index --quiet HEAD --; then
            git commit -snm "chore: updated GitHub Submodules at $(date '+%F %H:%M.%S')"
            git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD)
          fi
